import { Inter } from 'next/font/google'
import './globals.css'
import CustomNavbar from '@/components/CustomNavbar'
import Footer from '@/components/Footer'
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import UserProvider from '@/context/userProvider';

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          <CustomNavbar />
        
        <div className='my-4'>
        {children}
        </div>
        </UserProvider>
        
        <Footer/>

        
      </body>
    </html>
  )
}
 